### ISSUE TITLE
Please license under a mainstream Open Source license, please please

### ISSUE THREAD

**Issue by hartwork** [wleuschner/TessendorfWaves#1]
Hi!

We met at bhnt96 yesterday — very nice animation! I checked the code for a license and did not find any. Could you apply a mainstream Open Source license to the code so that it becomes truly free software? https://opensource.org/license/apache-2-0 or https://opensource.org/license/mit would work for instances. Thank you! :pray: 

Best, Sebastian

**Comment by wleuschner** [comment]
Is now licensed under MIT

**Comment by hartwork** [comment]
Thank you!
